import type { AnimationProject } from "./types";

export const demoProject: AnimationProject = {
  id: "starlight-seed",
  title: "The Lantern Beyond Saturn",
  logline: "A young courier restores a lost star by carrying its light home.",
  prompt: "A brave young cosmic courier finds a dim lost star and helps it return to its constellation.",
  updatedAt: new Date().toISOString(),
  assets: [],
  scenes: [
    {
      id: "scene-1",
      title: "A light in the dark",
      duration: 7,
      narration: "Mira was delivering a letter past Saturn when she spotted a tiny star drifting alone.",
      caption: "Mira was delivering a letter past Saturn when she spotted a tiny star drifting alone.",
      backgroundPrompt: "Saturn above a deep star field, luminous gold rings, purple nebula, portrait composition",
      characters: [{ name: "Mira", imagePrompt: "teen cosmic courier in a white and gold flight coat, lavender hair, expressive modern anime design", x: -0.17, y: -0.27, scale: 0.73, action: "float" }],
      objects: [{ name: "Lost star", imagePrompt: "small worried five-point star spirit glowing pale gold", x: 0.26, y: 0.15, scale: 0.25, action: "pulse" }],
      musicMood: "gentle cosmic wonder",
      sfx: [{ at: 2.8, note: 88, kind: "sparkle" }],
    },
    {
      id: "scene-2",
      title: "The simple plan",
      duration: 7,
      narration: "The star showed Mira an empty place in a distant constellation, so she promised to guide it home.",
      caption: "The star showed Mira an empty place in a distant constellation, so she promised to guide it home.",
      backgroundPrompt: "clear constellation map made of glowing gold stars in a blue and lavender nebula, no text",
      characters: [{ name: "Mira", imagePrompt: "teen cosmic courier in a white and gold flight coat, lavender hair", x: -0.24, y: -0.25, scale: 0.7, action: "enter-left" }],
      objects: [{ name: "Lost star", imagePrompt: "small hopeful five-point star spirit glowing gold", x: 0.24, y: 0.1, scale: 0.28, action: "glow" }],
      musicMood: "hopeful forward motion",
      sfx: [{ at: 1.2, note: 81, kind: "whoosh" }],
    },
    {
      id: "scene-3",
      title: "Through the storm",
      duration: 8,
      narration: "A meteor storm blocked the way, but Mira raised her golden lantern and revealed a safe path between the rocks.",
      caption: "A meteor storm blocked the way, but Mira raised her golden lantern and revealed a safe path between the rocks.",
      backgroundPrompt: "dynamic meteor storm in deep space opening around a path of golden light, modern anime portrait scene",
      characters: [{ name: "Mira", imagePrompt: "determined teen cosmic courier holding a radiant gold lantern", x: -0.1, y: -0.27, scale: 0.76, action: "shake" }],
      objects: [{ name: "Golden lantern", imagePrompt: "ornate small cosmic lantern radiating a strong gold beam", x: 0.19, y: 0.02, scale: 0.26, action: "glow" }],
      musicMood: "urgent heroic cosmic journey",
      sfx: [{ at: 1.1, note: 55, kind: "impact" }, { at: 4.2, note: 91, kind: "whoosh" }],
    },
    {
      id: "scene-4",
      title: "Home among the stars",
      duration: 8,
      narration: "The little star reached its place, the whole constellation shone again, and Mira continued her delivery beneath a brighter sky.",
      caption: "The little star reached its place, the whole constellation shone again, and Mira continued her delivery beneath a brighter sky.",
      backgroundPrompt: "triumphant complete constellation blazing in gold above Saturn, purple blue cosmic sky, portrait modern anime",
      characters: [{ name: "Mira", imagePrompt: "smiling teen cosmic courier in white and gold flight coat", x: -0.2, y: -0.29, scale: 0.72, action: "float" }],
      objects: [{ name: "Home star", imagePrompt: "joyful star spirit blazing bright gold within a constellation", x: 0.26, y: 0.23, scale: 0.28, action: "pulse" }],
      musicMood: "warm triumphant finale",
      sfx: [{ at: 1.6, note: 96, kind: "sparkle" }, { at: 3.2, note: 100, kind: "sparkle" }],
    },
  ],
};
